// <auto-generated />
namespace CaseStudy_19_1_23_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Innitial2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Innitial2));
        
        string IMigrationMetadata.Id
        {
            get { return "202301191100325_Innitial2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
